apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crawler
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      volumes:
       - name: cache-volume
         emptyDir: {}

      containers:
      - name: synergychat-crawler1
        image: bootdotdev/synergychat-crawler:latest

        volumeMounts:
          - name: cache-volume
            mountPath:  /cache

        env:  
          - name: CRAWLER_PORT
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT

          - name: CRAWLER_DB_PATH
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_DB_PATH

          - name: CRAWLER_KEYWORDS
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_KEYWORDS
            
            
      - name: synergychat-crawler2
        image: bootdotdev/synergychat-crawler:latest

        volumeMounts:
          - name: cache-volume
            mountPath:  /cache

        env:  
          - name: CRAWLER_PORT
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT_2

          - name: CRAWLER_DB_PATH
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_DB_PATH

          - name: CRAWLER_KEYWORDS
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_KEYWORDS

      - name: synergychat-crawler3
        image: bootdotdev/synergychat-crawler:latest

        volumeMounts:
          - name: cache-volume
            mountPath:  /cache

        env:  
          - name: CRAWLER_PORT
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT_3

          - name: CRAWLER_DB_PATH
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_DB_PATH

          - name: CRAWLER_KEYWORDS
            valueFrom:  
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_KEYWORDS
         
       
